id: P006820
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21693
  title: འཇམ་དབྱངས་བཞད་པའི་རྣམ་ཐར
  author: ''
  volumes:
    334caeb9f54146628b6cb8d8fdd2550c:
      image_group_id: I4238
      title: ''
      volume_number: 1
      total_pages: 282
      base_file: v001.txt
